ahome/urls.py
from django.urls import path
from . import views

app_name = 'ahome'

urlpatterns = [
    path('', views.apply_base , name='apply_base'),
    path('pjmanage/', views.pj_list , name='pj_list'),
    path('<int:abase_id>/', views.apply_detail , name='apply_detail'),
    path('ibju/', views.ibju_data , name='ibju_list'),
    path('onsale/', views.onsale_data , name='onsale_list'),
    path('pop/', views.pop_data , name='pop_list'),
    path('const/', views.const_data , name='const_list'),
    path('pjcode/', views.pjcode_data , name='pjcode_list'),
    path('rtech/', views.rtech_data, name='rtech_list'),
    path('img/', views.img_data, name='img_list'),
    path('table/', views.table_data, name='table_list'),
    path('tbl_kb50/', views.tbL_kb50, name='tbl_kb50'),
    path('tbl_pir/', views.tbl_pir, name='tbl_pir'),
    path('tbl_floorarea/', views.tbl_floorarea, name='tbl_floorarea'),
    path('tbl_allpj/', views.tbl_allpj, name='tbl_allpj'),
    path('rtp_bunyang/', views.rtp_bunyang, name='rtp_bunyang'),

]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from pybo.views import base_views

urlpatterns = [
    path('', base_views.home, name='home'),
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('ahome/', include('ahome.urls')),
    path('photo/', include('photo.urls')),
    path('rtp/', include('rtp.urls')),

    # path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rtp/urls.py
from django.urls import path
from . import views

app_name = 'rtp'

urlpatterns = [
    path('', views.search , name='search'),
    path('search_sma/', views.search_sma , name='search_sma'),
    path('search_big6/', views.search_big6 , name='search_big6'),
    path('search_dodo/', views.search_dodo , name='search_dodo'),
    path('rtp_bunyang/', views.bunyang_data, name='bunyang'),
    path('rtp_salesma/', views.salesma_data, name='salesma'),
    path('rtp_salebig6/', views.salebig6_data, name='salebig6'),
    path('rtp_saledodo/', views.saledodo_data, name='saledodo'),

]

ahome/models.py
# -*- coding: utf-8 -*-


from django.db import models

class Abase(models.Model):
    관리번호 = models.BigIntegerField(blank=True, null=True)
    모집공고일 = models.DateField(blank=True, null=True)
    단지명 = models.TextField(blank=True, null=True)
    주택구분 = models.TextField(blank=True, null=True)
    민영국민 = models.TextField(blank=True, null=True)
    분양구분 = models.TextField(blank=True, null=True)
    지역 = models.TextField(blank=True, null=True)
    자치구 = models.TextField(blank=True, null=True)
    주소지 = models.TextField(blank=True, null=True)
    세대수 = models.BigIntegerField(blank=True, null=True)
    계약시작일 = models.DateField(blank=True, null=True)
    계약종료일 = models.DateField(blank=True, null=True)
    건설사 = models.TextField(blank=True, null=True)
    시행사 = models.TextField(blank=True, null=True)
    입주시기 = models.TextField(blank=True, null=True)
    입주년도 = models.BigIntegerField(blank=True, null=True)
    모집공고월 = models.DateField(blank=True, null=True)


    def __str__(self):
        return self.단지명


class Adetail(models.Model):
    관리번호 = models.BigIntegerField(blank=True, null=True)
    모집공고일 = models.DateField(blank=True, null=True)
    지역 = models.TextField(blank=True, null=True)
    단지명 = models.TextField(blank=True, null=True)
    세대수 = models.BigIntegerField(blank=True, null=True)
    타입 = models.TextField(blank=True, null=True)
    공급면적 = models.TextField(blank=True, null=True)
    평형 = models.BigIntegerField(blank=True, null=True)
    타입세대수 = models.BigIntegerField(blank=True, null=True)
    타입최고가 = models.TextField(blank=True, null=True)
    공급평당가 = models.TextField(blank=True, null=True)
    모집공고월 = models.DateField(blank=True, null=True)
    abase = models.ForeignKey(Abase, on_delete=models.CASCADE)

    # class Meta:
    #     managed = False
    #     db_table = 'applydetail'

    def __str__(self):
        return self.단지명 + self.타입

class Pjmanage(models.Model):
    pjcode = models.CharField(max_length=10)
    optcode = models.CharField(max_length=10,null=True, blank=True)
    pjname = models.TextField(null=True, blank=True)
    end_day = models.DateTimeField(null=True, blank=True)
    come_day = models.DateTimeField(null=True, blank=True)
    dead_day = models.DateTimeField(null=True, blank=True)
    first_rate = models.FloatField()
    finance_rate = models.FloatField()
    end_rate = models.FloatField()
    end_profit = models.IntegerField()
    diff_ing = models.FloatField()
    fund = models.IntegerField()
    pf_remain = models.IntegerField()
    cash_year = models.IntegerField()
    cash_all = models.IntegerField()


class Ibju(models.Model):
    구분 = models.CharField(max_length=20)
    단지명 = models.CharField(max_length=50,null=True, blank=True)
    소재지 = models.CharField(max_length=50, null=True, blank=True)
    입주시기 = models.DateTimeField(null=True, blank=True)
    세대수 = models.IntegerField()
    매매시세 = models.IntegerField()
    평당분양가 = models.IntegerField()
    시공사 = models.CharField(max_length=20)
    시도 = models.CharField(max_length=20)
    자치구 = models.CharField(max_length=20)
    시도자치구 = models.CharField(max_length=20)
    기준월 = models.DateTimeField(null=True, blank=True)
    년 = models.IntegerField()

class Onsale(models.Model):
    시도자치구 = models.CharField(max_length=20)
    시도 = models.CharField(max_length=20, null=True, blank=True)
    자치구 = models.CharField(max_length=20, null=True, blank=True)
    미분양 = models.IntegerField()
    기준월 = models.DateField(null=True, blank=True)


class Pop(models.Model):
    시도자치구 = models.CharField(max_length=20)
    시도 = models.CharField(max_length=20, null=True, blank=True)
    자치구 = models.CharField(max_length=20, null=True, blank=True)
    총인구수 = models.IntegerField()
    세대수 = models.IntegerField()
    기준월 = models.DateField(null=True, blank=True)

class Const(models.Model):
    기준월 = models.DateField(null=True, blank=True)
    지수 = models.IntegerField()

class Pjcode(models.Model):
    구분 = models.CharField(max_length=2, null=True, blank=True)
    코드 = models.CharField(max_length=5, null=True, blank=True)
    내역 = models.CharField(max_length=50, null=True, blank=True)


class Rtech(models.Model):
    시도 = models.CharField(max_length=20, null=True, blank=True)
    자치구 = models.CharField(max_length=20, null=True, blank=True)
    아파트 = models.CharField(max_length=50, null=True, blank=True)
    주소 = models.CharField(max_length=50, null=True, blank=True)
    평당가 = models.IntegerField()
    국평가격 = models.IntegerField()

# class Unit(models.Model):
#     brandname = models.CharField(max_length=50, null=True, blank=True)
#     urls = models.CharField(max_length=50, null=True, blank=True)

ahome/views.py
# -*- coding: utf-8 -*-

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from ahome.models import Abase, Adetail, Pjmanage, Ibju, Onsale, Pop, Const, Pjcode, Rtech
from django.utils import timezone
from django.db.models import Q
import pandas as pd
import json


# @login_required(login_url='common:login')
def apply_base(request):
    kw = request.GET.get('kw', '')
    abase = Abase.objects.order_by('-모집공고일')
    if kw:
        abase = abase.filter(
            Q(지역__icontains=kw) |
            Q(건설사__icontains=kw)
        ).distinct()
    context = {'abase': abase, 'kw': kw}
    return render(request, 'ahome/apply_base.html', context)


def apply_detail(request, abase_id):
    abase = Abase.objects.get(id=abase_id)
    details = abase.adetail_set.all()
    context = {
        'abase': abase,
        'details': details
    }
    return render(request, 'ahome/apply_detail.html', context)

def pj_list(request):
    lists = Pjmanage.objects.all()
    context = { 'pjlist' : lists }
    return render(request, 'ahome/pj_manage.html', context)

def ibju_data(request):
    kw = request.GET.get('kw', '')
    ibju_list = Ibju.objects.order_by('입주시기').filter(입주시기__gte='2023-03-31').values
    if kw:
        ibju_list = ibju_list.filter(
            Q(구분__icontains=kw) |
            Q(시도__icontains=kw) |
            Q(자치구__icontains=kw) |
            Q(시공사__icontains=kw)
        ).distinct()
    context = { 'ibju_list' : ibju_list, 'kw': kw }

    return render(request, 'ahome/ibju_list.html', context)

def onsale_data(request):
    kw = request.GET.get('kw', '')
    onsale_list = Onsale.objects.order_by('-미분양')
    if kw:
        onsale_list = onsale_list.filter(
            Q(시도__icontains=kw) |
            Q(자치구__icontains=kw)
        ).distinct()
    context = { 'onsale_list' : onsale_list, 'kw': kw }

    return render(request, 'ahome/onsale_list.html', context)

def pop_data(request):
    kw = request.GET.get('kw', '')
    pop_list = Pop.objects.order_by('-총인구수')
    if kw:
        pop_list = pop_list.filter(
            Q(시도__icontains=kw) |
            Q(자치구__icontains=kw)
        ).distinct()
    context = { 'pop_list' : pop_list, 'kw': kw }

    return render(request, 'ahome/pop_list.html', context)

def const_data(request):
    kw = request.GET.get('kw', '')
    const_list = Const.objects.order_by('-지수')
    if kw:
        const_list = const_list.filter(
            Q(기준월__icontains=kw)
        ).distinct()
    context = { 'const_list' : const_list, 'kw': kw }

    return render(request, 'ahome/const_list.html', context)

def pjcode_data(request):
    kw = request.GET.get('kw', '')
    pjcode_list = Pjcode.objects.all()
    if kw:
        pjcode_list = pjcode_list.filter(
            Q(내역__icontains=kw)
        ).distinct()
    context = { 'pjcode_list' : pjcode_list, 'kw': kw }

    return render(request, 'ahome/pjcode_list.html', context)


def rtech_data(request):
    kw = request.GET.get('kw', '')
    rtech_list = Rtech.objects.all()
    if kw:
        rtech_list = rtech_list.filter(
            Q(시도__icontains=kw)|
            Q(자치구__icontains=kw)
        ).distinct()
    context = { 'rtech_list' : rtech_list, 'kw': kw }

    return render(request, 'ahome/rtech_list.html', context)


def img_data(request):
    return render(request, 'ahome/divcard_card.html')


def table_data(request):
    df = pd.read_csv('static/csv/실거래가격지수.csv', sep='\t')
    df = df.sort_values(by=['구분'], ascending=False)
    json_data = df.to_json(orient='records')
    data=[]
    data=json.loads(json_data)
    context = { 'data' : data }
    return render(request, 'ahome/table_list.html', context)

def tbL_kb50(request):
    df = pd.read_csv('static/csv/선도50지수_2305.csv', sep='\t')
    df = df.sort_values(by=['년월'], ascending=False)
    json_data = df.to_json(orient='records')
    data=[]
    data=json.loads(json_data)
    context = { 'data' : data }
    return render(request, 'ahome/tbl_kb50.html', context)


def tbl_pir(request):
    df = pd.read_csv('static/csv/pir_2303.csv', sep='\t')
    json_data = df.to_json(orient='records')
    data=[]
    data=json.loads(json_data)
    context = { 'data' : data }
    return render(request, 'ahome/tbl_pir.html', context)

def tbl_floorarea(request):
    df = pd.read_csv('static/csv/용적률.csv', sep='\t')
    json_data = df.to_json(orient='records')
    data=[]
    data=json.loads(json_data)
    context = { 'data' : data }
    return render(request, 'ahome/tbl_floorarea.html', context)

def rtp_bunyang(request):
    df = pd.read_csv('k:/django/pj_pybo/static/csv/bunyang.csv', sep=';')
    df = df.sort_values(by='기준월', ascending=False)
    json_data = df.to_json(orient='records')
    data = []
    data = json.loads(json_data)
    context = {'data': data[:500]}
    return render(request, 'ahome/rtp_bunyang.html', context)


def tbl_allpj(request):
    df = pd.read_csv('static/csv/all_pj.csv', sep='\t')
    json_data = df.to_json(orient='records')
    data=[]
    data=json.loads(json_data)
    context = { 'data' : data }
    return render(request, 'ahome/tbl_allpj.html', context)

templates/ahome/apply_base.html
{% extends 'base.html' %}

{% block content %}

<div class="container my-3">
    <!--검색기능-->
    <div class="col-4 input-group">
        <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
        </div>
    </div>
    <table class="table table-striped" style="font-size:12px">
        <p style="font-size:8;">* 지역, 건설사 검색</p>
        <thead>
        <tr>
            <th>모집공고일</th>
            <th>단지명</th>
            <th>주택구분</th>
            <th>민영국민</th>
            <th>지역</th>
            <th>자치구</th>
            <th>주소지</th>
            <th>세대수</th>
            <th>계약종료일</th>
            <th>건설사</th>
            <th>시행사</th>
            <th>입주시기</th>
        </tr>
        </br>
        </thead>

        <tbody>
        {% for value in abase %}
        <tr>
            <td style="width:80px;"> {{ value.모집공고일|date:'y-m-d' }}</td>
            <td><a href="{% url 'ahome:apply_detail' value.id %}">{{ value.단지명 }}</a></td>
            <td> {{ value.주택구분 }}</td>
            <td style="width:50px;"> {{ value.민영국민 }}</td>
            <td style="width:50px;"> {{ value.지역 }}</td>
            <td> {{ value.자치구 }}</td>
            <td> {{ value.주소지 }}</td>
            <td> {{ value.세대수 }}</td>
            <td style="width:80px;"> {{ value.계약종료일|date:'y-m-d' }}</td>
            <td> {{ value.건설사 }}</td>
            <td> {{ value.시행사 }}</td>
            <td> {{ value.입주시기 }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<!--kw를 get방식으로 요청하는 form추가-->
<form id="searchForm" method="get" action="{% url 'ahome:apply_base' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}

templates/ahome/apply_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <table class="table table-striped" style="font-size:12px">
        <p style="font-size:9;">* 평당가는 타입별 최고가의 평당가의 평균가격임</p>
        <div><a href="{% url 'ahome:apply_base' %}">Back</a></div>

        <thead>
        <tr>
            <th>모집공고일</th>
            <th>지역</th>
            <th>단지명</th>
            <th>타입</th>
            <th>공급면적</th>
            <th>평형</th>
            <th>타입세대수</th>
            <th>타입최고가</th>
            <th>공급평당가</th>
        </tr></br>
         </thead>
        <tbody>
        {% for value in details %}
        <tr>
            <td> {{ value.모집공고일 }}</td>
            <td> {{ value.지역 }}</td>
            <td> {{ value.단지명 }}</td>
            <td> {{ value.타입 }}</td>
            <td> {{ value.공급면적 }}</td>
            <td> {{ value.평형 }}</td>
            <td> {{ value.타입세대수 }}</td>
            <td> {{ value.타입최고가 }}</td>
            <td> {{ value.계약종료일 }}</td>
            <td> {{ value.공급평당가 }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/ahome/const_list.html
{% extends 'base.html' %}
{% load humanize %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <P>[KICT공사비원가관리센터]_건설공사비지수</P>
    <div class="row justify-content-between my-3">
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>

    <table class="table table-striped" style="width:25%; font-size:12px">
        <thead>
        <tr class="text-center">
            <th style="width:100px;">기준월</th>
            <th>지수</th>
        </tr>
        </thead>
        <tbody>
        {% for value in const_list %}
        <tr class="text-center">
            <td> {{ value.기준월|date:'y-m' }}</td>
            <td> {{ value.지수 }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<!--kw를 get방식으로 요청하는 form추가-->
<form id="searchForm" method="get" action="{% url 'ahome:const_list' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });
});

</script>
{% endblock %}

templates/ahome/ibju_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <P>[부동산지인]_입주예정자료</P>
    <div class="row justify-content-between my-3">
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
    <table class="table table-striped" style="font-size:12px">
        <thead>
        <tr class="text-center">
            <th style="width:100px;">구분</th>
            <th style="width:100px;">시도</th>
            <th style="width:80px;">자치구</th>
            <th style="width:200px;">단지명</th>
            <th>세대수</th>
            <th style="width:80px;">입주시기</th>
            <th style="width:200px;">소재지</th>
            <th>시공사</th>
        </tr>
        </thead>
        <tbody>
        {% for value in ibju_list %}
        <tr>
            <td> {{ value.구분 }}</td>
            <td> {{ value.시도 }}</td>
            <td> {{ value.자치구 }}</td>
            <td> {{ value.단지명 }}</td>
            <td> {{ value.세대수 }}</td>
            <td> {{ value.입주시기|date:'y-m' }}</td>
            <td> {{ value.소재지 }}</td>
            <td> {{ value.시공사 }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<!--kw를 get방식으로 요청하는 form추가-->
<form id="searchForm" method="get" action="{% url 'ahome:ibju_list' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}

templates/ahome/onsale_list.html
{% extends 'base.html' %}
{% load humanize %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <P>[국토교통부 통계누리]_시군구별 미분양현황</P>
    <div class="row justify-content-between my-3">
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
    <table class="table table-striped" style="width:50%; font-size:12px">
        <thead>
        <tr class="text-center">
            <th style="width:100px;">시도</th>
            <th>자치구</th>
            <th>미분양</th>
            <th>기준월</th>
        </tr>
        </thead>
        <tbody>
        {% for value in onsale_list %}
        <tr class="text-center">
            <td> {{ value.시도 }}</td>
            <td> {{ value.자치구 }}</td>
            <td> {{ value.미분양|intcomma }}</td>
            <td> {{ value.기준월|date:'y-m-d' }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<!--kw를 get방식으로 요청하는 form추가-->
<form id="searchForm" method="get" action="{% url 'ahome:onsale_list' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });
});

</script>
{% endblock %}

templates/ahome/pjcode_list.html
{% extends 'base.html' %}
{% load humanize %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <P>PJ_CODE</P>
    <div class="row justify-content-between my-3">
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>

    <table class="table table-striped" style="width:50%; font-size:12px">
        <thead>
        <tr class="text-center">
            <th style="width:100px;">코드</th>
            <th>내역</th>
        </tr>
        </thead>
        <tbody>
        {% for value in pjcode_list %}
        <tr>
            <td> {{ value.코드 }}</td>
            <td> {{ value.내역 }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<!--kw를 get방식으로 요청하는 form추가-->
<form id="searchForm" method="get" action="{% url 'ahome:pjcode_list' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });
});

</script>
{% endblock %}

templates/ahome/pop_list.html
{% extends 'base.html' %}
{% load humanize %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <P>행정안전부 인구등록자료</P>
    <div class="row justify-content-between my-3">
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>

    <table class="table table-striped" style="width:50%; font-size:12px">
        <thead>
        <tr>
            <th style="width:100px;">시도</th>
            <th>자치구</th>
            <th>총인구수</th>
            <th>세대수</th>
            <th>기준월</th>
        </tr>
        </thead>
        <tbody>
        {% for value in pop_list %}
        <tr>
            <td> {{ value.시도 }}</td>
            <td> {{ value.자치구 }}</td>
            <td> {{ value.총인구수|intcomma }}</td>
            <td> {{ value.세대수|intcomma }}</td>
            <td> {{ value.기준월|date:'y-m-d' }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<!--kw를 get방식으로 요청하는 form추가-->
<form id="searchForm" method="get" action="{% url 'ahome:pop_list' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });
});

</script>
{% endblock %}

templates/ahome/rtech_list.html
{% extends 'base.html' %}
{% load humanize %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <P>부동산원 부동산테크 지역동향분석 단지 TOP10</P>
    <div class="row justify-content-between my-3">
        <div class="col-6 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append" style="width:100%;">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>

    <table class="table table-striped" style="width:100%; font-size:12px">
        <thead>
        <tr style="color:white; background-color:black;">
            <th style="width:100px;">시도</th>
            <th>자치구</th>
            <th>아파트</th>
            <th>주소</th>
            <th>평당가</th>
            <th>국평가격</th>
        </tr>
        </thead>
        <tbody>
        {% for value in rtech_list %}
        <tr>
            <td> {{ value.시도 }}</td>
            <td> {{ value.자치구 }}</td>
            <td> {{ value.아파트|intcomma }}</td>
            <td> {{ value.주소 }}</td>
            <td> {{ value.평당가|intcomma }}</td>
            <td> {{ value.국평가격|intcomma }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<!--kw를 get방식으로 요청하는 form추가-->
<form id="searchForm" method="get" action="{% url 'ahome:rtech_list' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}

templates/ahome/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

emmet의 활용
! + tab
div. + tab
div# + tab
div > ul > li + tab


</body>
</html>