config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from pybo.views import base_views

urlpatterns = [
    path('', base_views.home, name='home'),
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('ahome/', include('ahome.urls')),
    path('photo/', include('photo.urls')),
    path('rtp/', include('rtp.urls')),

    # path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rtp/urls.py
from django.urls import path
from . import views

app_name = 'rtp'

urlpatterns = [
    path('', views.search , name='search'),
    path('search_sma/', views.search_sma , name='search_sma'),
    path('search_big6/', views.search_big6 , name='search_big6'),
    path('search_dodo/', views.search_dodo , name='search_dodo'),
    path('rtp_bunyang/', views.bunyang_data, name='bunyang'),
    path('rtp_salesma/', views.salesma_data, name='salesma'),
    path('rtp_salebig6/', views.salebig6_data, name='salebig6'),
    path('rtp_saledodo/', views.saledodo_data, name='saledodo'),

]

rtp/models.py
from django.db import models

class Bunyang(models.Model):
    광역시도 = models.TextField(blank=True, null=True)
    시자치구 = models.TextField(blank=True, null=True)
    법정동 = models.TextField(blank=True, null=True)
    아파트 = models.TextField(blank=True, null=True)
    전용면적 = models.BigIntegerField(blank=True, null=True)
    거래금액 = models.BigIntegerField(blank=True, null=True)
    층 = models.BigIntegerField(blank=True, null=True)
    년 = models.BigIntegerField(blank=True, null=True)
    월 = models.BigIntegerField(blank=True, null=True)
    전용 = models.BigIntegerField(blank=True, null=True)
    거래유형 = models.TextField(blank=True, null=True)
    기준월 = models.DateField(blank=True, null=True)


class SaleSma(models.Model):
    광역시도 = models.TextField(blank=True, null=True)
    시자치구 = models.TextField(blank=True, null=True)
    법정동 = models.TextField(blank=True, null=True)
    아파트 = models.TextField(blank=True, null=True)
    전용면적 = models.FloatField(blank=True, null=True)
    거래금액 = models.BigIntegerField(blank=True, null=True)
    층 = models.TextField(blank=True, null=True)
    건축년도 = models.BigIntegerField(blank=True, null=True)
    년 = models.BigIntegerField(blank=True, null=True)
    월 = models.BigIntegerField(blank=True, null=True)
    전용 = models.BigIntegerField(blank=True, null=True)
    거래유형 = models.TextField(blank=True, null=True)
    기준월 = models.DateField(blank=True, null=True)


class SaleBig6(models.Model):
    광역시도 = models.TextField(blank=True, null=True)
    시자치구 = models.TextField(blank=True, null=True)
    법정동 = models.TextField(blank=True, null=True)
    아파트 = models.TextField(blank=True, null=True)
    전용면적 = models.FloatField(blank=True, null=True)
    거래금액 = models.BigIntegerField(blank=True, null=True)
    층 = models.TextField(blank=True, null=True)
    건축년도 = models.BigIntegerField(blank=True, null=True)
    년 = models.BigIntegerField(blank=True, null=True)
    월 = models.BigIntegerField(blank=True, null=True)
    전용 = models.BigIntegerField(blank=True, null=True)
    거래유형 = models.TextField(blank=True, null=True)
    기준월 = models.DateField(blank=True, null=True)


class SaleDodo(models.Model):
    광역시도 = models.TextField(blank=True, null=True)
    시자치구 = models.TextField(blank=True, null=True)
    법정동 = models.TextField(blank=True, null=True)
    아파트 = models.TextField(blank=True, null=True)
    전용면적 = models.FloatField(blank=True, null=True)
    거래금액 = models.BigIntegerField(blank=True, null=True)
    층 = models.TextField(blank=True, null=True)
    건축년도 = models.BigIntegerField(blank=True, null=True)
    년 = models.BigIntegerField(blank=True, null=True)
    월 = models.BigIntegerField(blank=True, null=True)
    전용 = models.BigIntegerField(blank=True, null=True)
    거래유형 = models.TextField(blank=True, null=True)
    기준월 = models.DateField(blank=True, null=True)

rtp/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from rtp.models import Bunyang, SaleSma, SaleBig6, SaleDodo
from django.utils import timezone
from django.db.models import Q
import pandas as pd
import json


def search(request):
    return render(request, 'rtp/search_form.html')

def search_sma(request):
    return render(request, 'rtp/search_form_sma.html')

def search_big6(request):
    return render(request, 'rtp/search_form_big6.html')

def search_dodo(request):
    return render(request, 'rtp/search_form_dodo.html')


def bunyang_data(request):
    시도 = request.POST.get("city")
    if request.POST.get("county") == '전체':
        자치구 = ""
    else:
        자치구 = request.POST.get("county")
    조회시작 = request.POST.get("start")
    조회종료 = request.POST.get("end")
    전용B = request.POST.get("size_begin")
    전용E = request.POST.get("size_end")

    bunyang_list = Bunyang.objects.all()
    bunyang_list = bunyang_list.filter(광역시도=시도, 시자치구__contains=자치구, 기준월__gte=조회시작, 기준월__lte=조회종료, 전용__gte=전용B, 전용__lte=전용E).order_by('-기준월','-거래금액')

    context = {'data': bunyang_list }
    return render(request, 'rtp/bunyang_list.html', context)


def salesma_data(request):
    시도 = request.POST.get("city")
    if request.POST.get("county") == '전체':
        자치구 = ""
    else:
        자치구 = request.POST.get("county")
    조회시작 = request.POST.get("start")
    조회종료 = request.POST.get("end")
    전용B = request.POST.get("size_begin")
    전용E = request.POST.get("size_end")

    salesma_list = SaleSma.objects.all()
    salesma_list = salesma_list.filter(광역시도=시도, 시자치구__contains=자치구, 기준월__gte=조회시작, 기준월__lte=조회종료, 전용__gte=전용B, 전용__lte=전용E).order_by('-기준월','-거래금액')

    context = {'data': salesma_list }
    return render(request, 'rtp/salesma_list.html', context)

def salebig6_data(request):
    시도 = request.POST.get("city")
    if request.POST.get("county") == '전체':
        자치구 = ""
    else:
        자치구 = request.POST.get("county")
    조회시작 = request.POST.get("start")
    조회종료 = request.POST.get("end")
    전용B = request.POST.get("size_begin")
    전용E = request.POST.get("size_end")

    salebig6_list = SaleBig6.objects.all()
    salebig6_list = salebig6_list.filter(광역시도=시도, 시자치구__contains=자치구, 기준월__gte=조회시작, 기준월__lte=조회종료, 전용__gte=전용B, 전용__lte=전용E).order_by('-기준월','-거래금액')

    context = {'data': salebig6_list }
    return render(request, 'rtp/salebig6_list.html', context)


def saledodo_data(request):
    시도 = request.POST.get("city")
    if request.POST.get("county") == '전체':
        자치구 = ""
    else:
        자치구 = request.POST.get("county")
    조회시작 = request.POST.get("start")
    조회종료 = request.POST.get("end")
    전용B = request.POST.get("size_begin")
    전용E = request.POST.get("size_end")

    saledodo_list = SaleDodo.objects.all()
    saledodo_list = saledodo_list.filter(광역시도=시도, 시자치구__contains=자치구, 기준월__gte=조회시작, 기준월__lte=조회종료, 전용__gte=전용B, 전용__lte=전용E).order_by('-기준월','-거래금액')

    context = {'data': saledodo_list }
    return render(request, 'rtp/saledodo_list.html', context)

templates/rtp/bunyang_list.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}

<div class="container">
    <table class="table table-striped" style="font-size:12px">
        <hr>
        <h5>실거래가-분양권</h5>
        <p><a href="{% url 'rtp:search' %}">검색화면으로</a></p>
        <thead>
        <tr>
            <th>광역시도</th>
            <th>시자치구</th>
            <th>법정동</th>
            <th>아파트</th>
            <th>전용면적</th>
            <th>전용</th>
            <th>거래금액</th>
            <th>층</th>
            <th>구분</th>
            <th>거래유형</th>
            <th>기준월</th>
        </tr></br>
         </thead>
        <tbody>
        {% for value in data %}
        <tr>
            <td> {{ value.광역시도 }}</td>
            <td> {{ value.시자치구 }}</td>
            <td> {{ value.법정동 }}</td>
            <td> {{ value.아파트 }}</td>
            <td> {{ value.전용면적 }}</td>
            <td> {{ value.전용 }}</td>
            <td> {{ value.거래금액|intcomma }}</td>
            <td> {{ value.층 }}</td>
            <td> {{ value.구분 }}</td>
            <td> {{ value.거래유형 }}</td>
            <td> {{ value.기준월 }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/rtp/salebig6_list.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}

<div class="container">
    <table class="table table-striped" style="font-size:12px">
        <hr>
        <h5>실거래가-매매_지방광역시</h5>
        <p><a href="{% url 'rtp:search_big6' %}">검색화면으로</a></p>
        <thead>
        <tr>
            <th>광역시도</th>
            <th>시자치구</th>
            <th>법정동</th>
            <th>아파트</th>
            <th>전용면적</th>
            <th>전용</th>
            <th>거래금액</th>
            <th>층</th>
            <th>구분</th>
            <th>거래유형</th>
            <th>기준월</th>
        </tr>
        </br>
        </thead>
        <tbody>
        {% for value in data %}
        <tr>
            <td> {{ value.광역시도 }}</td>
            <td> {{ value.시자치구 }}</td>
            <td> {{ value.법정동 }}</td>
            <td> {{ value.아파트 }}</td>
            <td> {{ value.전용면적 }}</td>
            <td> {{ value.전용 }}</td>
            <td> {{ value.거래금액|intcomma }}</td>
            <td> {{ value.층 }}</td>
            <td> {{ value.구분 }}</td>
            <td> {{ value.거래유형 }}</td>
            <td> {{ value.기준월 }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/rtp/saledodo_list.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}

<div class="container">
    <table class="table table-striped" style="font-size:12px">
        <hr>
        <h5>실거래가-매매_팔도</h5>
        <p><a href="{% url 'rtp:search_dodo' %}">검색화면으로</a></p>
        <thead>
        <tr>
            <th>광역시도</th>
            <th>시자치구</th>
            <th>법정동</th>
            <th>아파트</th>
            <th>전용면적</th>
            <th>전용</th>
            <th>거래금액</th>
            <th>층</th>
            <th>구분</th>
            <th>거래유형</th>
            <th>기준월</th>
        </tr></br>
         </thead>
        <tbody>
        {% for value in data %}
        <tr>
            <td> {{ value.광역시도 }}</td>
            <td> {{ value.시자치구 }}</td>
            <td> {{ value.법정동 }}</td>
            <td> {{ value.아파트 }}</td>
            <td> {{ value.전용면적 }}</td>
            <td> {{ value.전용 }}</td>
            <td> {{ value.거래금액|intcomma }}</td>
            <td> {{ value.층 }}</td>
            <td> {{ value.구분 }}</td>
            <td> {{ value.거래유형 }}</td>
            <td> {{ value.기준월 }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/rtp/salesma_list.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}

<div class="container">
    <table class="table table-striped" style="font-size:12px">
        <hr>
        <h5>실거래가-매매_수도권</h5>
        <p><a href="{% url 'rtp:search_sma' %}">검색화면으로</a></p>
        <thead>
        <tr>
            <th>광역시도</th>
            <th>시자치구</th>
            <th>법정동</th>
            <th>아파트</th>
            <th>전용면적</th>
            <th>전용</th>
            <th>거래금액</th>
            <th>층</th>
            <th>구분</th>
            <th>거래유형</th>
            <th>기준월</th>
        </tr></br>
         </thead>
        <tbody>
        {% for value in data %}
        <tr>
            <td> {{ value.광역시도 }}</td>
            <td> {{ value.시자치구 }}</td>
            <td> {{ value.법정동 }}</td>
            <td> {{ value.아파트 }}</td>
            <td> {{ value.전용면적 }}</td>
            <td> {{ value.전용 }}</td>
            <td> {{ value.거래금액|intcomma }}</td>
            <td> {{ value.층 }}</td>
            <td> {{ value.구분 }}</td>
            <td> {{ value.거래유형 }}</td>
            <td> {{ value.기준월 }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/rtp/search_form.html
{% extends 'base.html' %}

{% block content %}
<script language='javascript'>
<!--
     var cnt = new Array();
     cnt[0] = new Array('전체');
     cnt[1] = new Array('전체','강남구','강동구','강북구','강서구','관악구','광진구','구로구','금천구','노원구','도봉구','동대문구','동작구','마포구','서대문구','서초구','성동구','성북구','송파구','양천구','영등포구','용산구','은평구','종로구','중구','중랑구');
     cnt[2] = new Array('전체','강서구','금정구','남구','동구','동래구','부산진구','북구','사상구','사하구','서구','수영구','연제구','영도구','중구','해운대구','기장군');
     cnt[3] = new Array('전체','남구','달서구','동구','북구','서구','수성구','중구','달성군');
     cnt[4] = new Array('전체','계양구','남구','남동구','동구','부평구','서구','연수구','중구','강화군','옹진군');
     cnt[5] = new Array('전체','광산구','남구','동구','북구','서구');
     cnt[6] = new Array('전체','대덕구','동구','서구','유성구','중구');
     cnt[7] = new Array('전체','남구','동구','북구','중구','울주군');
     cnt[8] = new Array('전체','고양시','과천시','광명시','구리시','군포시','남양주시','동두천시','부천시','성남시','수원시','시흥시','안산시','안양시','오산시','의왕시','의정부시','평택시','하남시','가평군','광주시','김포시','안성시','양주군','양평군','여주군','연천군','용인시','이천군','파주시','포천시','화성시');
     cnt[9] = new Array('전체','강릉시','동해시','삼척시','속초시','원주시','춘천시','태백시','고성군','양구군','양양군','영월군','인제군','정선군','철원군','평창군','홍천군','화천군','황성군');
     cnt[10] = new Array('전체','제천시','청주시','충주시','괴산군','단양군','보은군','영동군','옥천군','음성군','진천군','청원군');
     cnt[11] = new Array('전체','공주시','보령시','서산시','아산시','천안시','금산군','논산군','당진군','부여군','서천군','연기군','예산군','청양군','태안군','홍성군');
     cnt[12] = new Array('전체','군산시','김제시','남원시','익산시','전주시','정읍시','고창군','무주군','부안군','순창군','완주군','임실군','장수군','진안군');
     cnt[13] = new Array('전체','광양시','나주시','목포시','순천시','여수시','여천시','강진군','고흥군','곡성군','구례군','담양군','무안군','보성군','신안군','여천군','영광군','영암군','완도군','장성군','장흥군','진도군','함평군','해남군','화순군');
     cnt[14] = new Array('전체','경산시','경주시','구미시','김천시','문겅시','상주시','안동시','영주시','영천시','포항시','고령군','군위군','봉화군','성주군','영덕군','영양군','예천군','울릉군','울진군','의성군','청도군','청송군','칠곡군');
     cnt[15] = new Array('전체','거제시','김해시','마산시','밀양시','사천시','울산시','진주시','진해시','창원시','통영시','거창군','고성군','남해군','산청군','양산시','의령군','창녕군','하동군','함안군','함양군','합천군');
     cnt[16] = new Array('전체','서귀포시','제주시','남제주군','북제주군');

     function change(add) {
     sel=document.form.county
       /* 옵션메뉴삭제 */
       for (i=sel.length-1; i>=0; i--){
         sel.options[i] = null
         }
       /* 옵션박스추가 */
       for (i=0; i < cnt[add].length;i++){
                         sel.options[i] = new Option(cnt[add][i], cnt[add][i]);
         }
     }
     <!--var date = new Date()-->
     <!--y = date.getFullYear()-->
     <!--m = date.getMonth()-->
     <!--eofmonth= new Date(y,m+1,0)-->
     <!--document.getElementById("end").setAttribute("max", eofmonth);-->
//-->
</script>

<div class="container" style="font-size:14px">
    <hr>
    <br>
    <h4>분양권 실거래가 조회</h4>
    <div class="row">
        <form name=form method=post action="{% url 'rtp:bunyang' %}">
            {% csrf_token %}

            <div style="padding:10px">광역시도:
                <select name='city' onchange="change(this.selectedIndex);" class=input style="width:150px;">
                    <option value='전체'>전체</option>
                    <option value='서울특별시'>서울특별시</option>
                    <option value='부산광역시'>부산광역시</option>
                    <option value='대구광역시'>대구광역시</option>
                    <option value='인천광역시'>인천광역시</option>
                    <option value='광주광역시'>광주광역시</option>
                    <option value='대전광역시'>대전광역시</option>
                    <option value='울산광역시'>울산광역시</option>
                    <option value='경기도'>경기도</option>
                    <option value='강원도'>강원도</option>
                    <option value='충청북도'>충청북도</option>
                    <option value='충청남도'>충청남도</option>
                    <option value='전라북도'>전라북도</option>
                    <option value='전라남도'>전라남도</option>
                    <option value='경상북도'>경상북도</option>
                    <option value='경상남도'>경상남도</option>
                    <option value='제주특별자치시'>제주도</option>
                </select>
            </div>
            <div style="padding:10px">시자치군:
                <select name='county' class=select style="width:150px;">
                    <option value=''>전체</option>
                </select>
            </div>
            <br/>
            <div style="padding:10px">
                <label for="size_begin">전 용 면 적:</label>
                <input type="text" id="size_begin" name="size_begin" , min="40" value="59" style="width:40px;">
                <label for="size_end">~</label>
                <input type="text" id="size_end" name="size_end" , max="150" , value="85" style="width:40px;">
            </div>
            <br/>
            <div style="padding:10px">
                <label for="start">조회시작월:</label>
                <input type="date" id="start" name="start" , min="2022-12-31" value="2023-01-31" style="width:150px;">
            </div>
            <div style="padding:10px">
                <label for="end">조회종료월:</label>
                <input type="date" id="end" name="end" , max="" value='2023-05-31' style="width:150px;">
            </div>
            <br/>
            <div style="text-align:center; padding:10px; width:150px">
                <button type="submit">검색</button>
            </div>
        </form>
        </fieldset>
    </div>
</div>
{% endblock %}

templates/rtp/search_form_big6.html
{% extends 'base.html' %}

{% block content %}
<script language='javascript'>
<!--
     var cnt = new Array();
     cnt[0] = new Array('전체');
     cnt[1] = new Array('전체','강서구','금정구','남구','동구','동래구','부산진구','북구','사상구','사하구','서구','수영구','연제구','영도구','중구','해운대구','기장군');
     cnt[2] = new Array('전체','남구','달서구','동구','북구','서구','수성구','중구','달성군');
     cnt[3] = new Array('전체','광산구','남구','동구','북구','서구');
     cnt[4] = new Array('전체','대덕구','동구','서구','유성구','중구');
     cnt[5] = new Array('전체','남구','동구','북구','중구','울주군');
     cnt[6] = new Array('전체','세종특별자치시');

     function change(add) {
     sel=document.form.county
       /* 옵션메뉴삭제 */
       for (i=sel.length-1; i>=0; i--){
         sel.options[i] = null
         }
       /* 옵션박스추가 */
       for (i=0; i < cnt[add].length;i++){
                         sel.options[i] = new Option(cnt[add][i], cnt[add][i]);
         }
     }
     <!--var date = new Date()-->
     <!--y = date.getFullYear()-->
     <!--m = date.getMonth()-->
     <!--eofmonth= new Date(y,m+1,0)-->
     <!--document.getElementById("end").setAttribute("max", eofmonth);-->
//-->
</script>

<div class="container" style="font-size:14px">
    <hr>
    <br>
    <h4>아파트 실거래가조회[지방광역시]</h4>
    <div class="row">
        <form name=form method=post action="{% url 'rtp:salebig6' %}">
            {% csrf_token %}

            <div style="padding:10px">광역시도:
                <select name='city' onchange="change(this.selectedIndex);" class=input style="width:150px;">
                    <option value='전체'>전체</option>
                    <option value='부산광역시'>부산광역시</option>
                    <option value='대구광역시'>대구광역시</option>
                    <option value='광주광역시'>광주광역시</option>
                    <option value='대전광역시'>대전광역시</option>
                    <option value='울산광역시'>울산광역시</option>
                    <option value='세종특별자치시'>세종특별자치시</option>
                </select>
            </div>
            <div style="padding:10px">시자치군:
                <select name='county' class=select style="width:150px;">
                    <option value=''>전체</option>
                </select>
            </div>
            <br/>
            <div style="padding:10px">
                <label for="size_begin">전 용 면 적:</label>
                <input type="text" id="size_begin" name="size_begin" , min="40" value="59" style="width:40px;">
                <label for="size_end">~</label>
                <input type="text" id="size_end" name="size_end" , max="150" , value="85" style="width:40px;">
            </div>
            <br/>
            <div style="padding:10px">
                <label for="start">조회시작월:</label>
                <input type="date" id="start" name="start" , min="2022-12-31" value="2023-01-31" style="width:150px;">
            </div>
            <div style="padding:10px">
                <label for="end">조회종료월:</label>
                <input type="date" id="end" name="end" , max="" value='2023-05-31' style="width:150px;">
            </div>
            <br/>
            <div style="text-align:center; padding:10px; width:150px">
                <button type="submit">검색</button>
            </div>
        </form>
        </fieldset>
    </div>
</div>
{% endblock %}

templates/rtp/search_form_dodo.html
{% extends 'base.html' %}

{% block content %}
<script language='javascript'>
<!--
     var cnt = new Array();
     cnt[0] = new Array('전체');
     cnt[1] = new Array('전체','강릉시','동해시','삼척시','속초시','원주시','춘천시','태백시','고성군','양구군','양양군','영월군','인제군','정선군','철원군','평창군','홍천군','화천군','황성군');
     cnt[2] = new Array('전체','제천시','청주시','충주시','괴산군','단양군','보은군','영동군','옥천군','음성군','진천군','청원군');
     cnt[3] = new Array('전체','공주시','보령시','서산시','아산시','천안시','금산군','논산군','당진군','부여군','서천군','연기군','예산군','청양군','태안군','홍성군');
     cnt[4] = new Array('전체','군산시','김제시','남원시','익산시','전주시','정읍시','고창군','무주군','부안군','순창군','완주군','임실군','장수군','진안군');
     cnt[5] = new Array('전체','광양시','나주시','목포시','순천시','여수시','여천시','강진군','고흥군','곡성군','구례군','담양군','무안군','보성군','신안군','여천군','영광군','영암군','완도군','장성군','장흥군','진도군','함평군','해남군','화순군');
     cnt[6] = new Array('전체','경산시','경주시','구미시','김천시','문겅시','상주시','안동시','영주시','영천시','포항시','고령군','군위군','봉화군','성주군','영덕군','영양군','예천군','울릉군','울진군','의성군','청도군','청송군','칠곡군');
     cnt[7] = new Array('전체','거제시','김해시','마산시','밀양시','사천시','울산시','진주시','진해시','창원시','통영시','거창군','고성군','남해군','산청군','양산시','의령군','창녕군','하동군','함안군','함양군','합천군');
     cnt[8] = new Array('전체','서귀포시','제주시','남제주군','북제주군');

     function change(add) {
     sel=document.form.county
       /* 옵션메뉴삭제 */
       for (i=sel.length-1; i>=0; i--){
         sel.options[i] = null
         }
       /* 옵션박스추가 */
       for (i=0; i < cnt[add].length;i++){
                         sel.options[i] = new Option(cnt[add][i], cnt[add][i]);
         }
     }
     <!--var date = new Date()-->
     <!--y = date.getFullYear()-->
     <!--m = date.getMonth()-->
     <!--eofmonth= new Date(y,m+1,0)-->
     <!--document.getElementById("end").setAttribute("max", eofmonth);-->
//-->
</script>

<div class="container" style="font-size:14px">
    <hr>
    <br>
    <h4>아파트 실거래가조회[팔도]</h4>
    <div class="row">
        <form name=form method=post action="{% url 'rtp:saledodo' %}">
            {% csrf_token %}

            <div style="padding:10px">광역시도:
                <select name='city' onchange="change(this.selectedIndex);" class=input style="width:150px;">
                    <option value='전체'>전체</option>
                    <option value='강원도'>강원도</option>
                    <option value='충청북도'>충청북도</option>
                    <option value='충청남도'>충청남도</option>
                    <option value='전라북도'>전라북도</option>
                    <option value='전라남도'>전라남도</option>
                    <option value='경상북도'>경상북도</option>
                    <option value='경상남도'>경상남도</option>
                    <option value='제주특별자치시'>제주도</option>
                </select>
            </div>
            <div style="padding:10px">시자치군:
                <select name='county' class=select style="width:150px;">
                    <option value=''>전체</option>
                </select>
            </div>
            <br/>
            <div style="padding:10px">
                <label for="size_begin">전 용 면 적:</label>
                <input type="text" id="size_begin" name="size_begin" , min="40" value="59" style="width:40px;">
                <label for="size_end">~</label>
                <input type="text" id="size_end" name="size_end" , max="150" , value="85" style="width:40px;">
            </div>
            <br/>
            <div style="padding:10px">
                <label for="start">조회시작월:</label>
                <input type="date" id="start" name="start" , min="2022-12-31" value="2023-01-31" style="width:150px;">
            </div>
            <div style="padding:10px">
                <label for="end">조회종료월:</label>
                <input type="date" id="end" name="end" , max="" value='2023-05-31' style="width:150px;">
            </div>
            <br/>
            <div style="text-align:center; padding:10px; width:150px">
                <button type="submit">검색</button>
            </div>
        </form>
        </fieldset>
    </div>
</div>
{% endblock %}