ahome/urls.py
from django.urls import path
from . import views

app_name = 'ahome'

urlpatterns = [
    path('', views.apply_base , name='apply_base'),
    path('pjmanage/', views.pj_list , name='pj_list'),
    path('<int:abase_id>/', views.apply_detail , name='apply_detail'),
    path('ibju/', views.ibju_data , name='ibju_list'),
    path('onsale/', views.onsale_data , name='onsale_list'),
    path('pop/', views.pop_data , name='pop_list'),
    path('const/', views.const_data , name='const_list'),
    path('pjcode/', views.pjcode_data , name='pjcode_list'),
    path('rtech/', views.rtech_data, name='rtech_list'),
    path('img/', views.img_data, name='img_list'),
    path('table/', views.table_data, name='table_list'),
    path('tbl_kb50/', views.tbL_kb50, name='tbl_kb50'),
    path('tbl_pir/', views.tbl_pir, name='tbl_pir'),
    path('tbl_floorarea/', views.tbl_floorarea, name='tbl_floorarea'),
    path('tbl_allpj/', views.tbl_allpj, name='tbl_allpj'),
    path('rtp_bunyang/', views.rtp_bunyang, name='rtp_bunyang'),

]

common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from pybo.views import base_views

urlpatterns = [
    path('', base_views.home, name='home'),
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('ahome/', include('ahome.urls')),
    path('photo/', include('photo.urls')),
    path('rtp/', include('rtp.urls')),

    # path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from django.views.generic.detail import DetailView
from .views import *
from .models import Photo, Brand, Unit, Viewimage

app_name = "photo"

urlpatterns = [
    path('', photo_list, name='photo_list'),
    path('detail/<int:pk>/', DetailView.as_view(model=Photo,
         template_name='photo/detail.html'), name='photo_detail'),
    path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
    path('delete/<int:pk>/', PhotoDeleteView.as_view(), name='photo_delete'),
    path('update/<int:pk>/', PhotoUpdateView.as_view(), name='photo_update'),
    path('brand/', brand_list, name = 'brand_list'),
    path('brand/<int:brand_id>/', img_list, name = 'img_list'),
    path('viewimg/', viewimg_list, name = 'viewimg_list'),

]

pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

rtp/urls.py
from django.urls import path
from . import views

app_name = 'rtp'

urlpatterns = [
    path('', views.search , name='search'),
    path('search_sma/', views.search_sma , name='search_sma'),
    path('search_big6/', views.search_big6 , name='search_big6'),
    path('search_dodo/', views.search_dodo , name='search_dodo'),
    path('rtp_bunyang/', views.bunyang_data, name='bunyang'),
    path('rtp_salesma/', views.salesma_data, name='salesma'),
    path('rtp_salebig6/', views.salebig6_data, name='salebig6'),
    path('rtp_saledodo/', views.saledodo_data, name='saledodo'),

]

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.db.models import Q, Count
from django.shortcuts import render, get_object_or_404

from ..models import Question


def home(request):
    return render(request, 'home.html')


def index(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')  # 정렬기준

    # 정렬
    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:  # recent
        question_list = Question.objects.order_by('-create_date')

    # 검색
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이검색
        ).distinct()

    # 페이징처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so': so}  # <------ so 추가
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
            integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
            integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
            crossorigin="anonymous"></script>
    {% block extra-style %}
    {% endblock %}
    <title>Mysite</title>
</head>

<body>
<!-- 기본 navbar삽입 -->
{% include "navbar2.html" %}

<!-- 기본 템플릿 안에 삽입될 콘텐츠 블럭 -->
{% block content %}
{% endblock %}

<!-- jQuery JS -->
<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>

<!-- 자바스크립트 블럭 -->
{% block script %}
{% endblock %}

</body>
</html>

templates/base_ahome.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Mysite</title>
</head>
<body>
{% include "base.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/base_side.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    {% block extra-style %}
    {% endblock %}
    <title>Mysite</title>
</head>

<body>
<!-- 기본 navbar삽입 -->
{% include "navbar.html" %}

<!-- 기본 템플릿 안에 삽입될 콘텐츠 블럭 -->

<div class="container mt-3">
    <div class="row">
        <div class="col-sm-12 col-md-3 col-lg-2 p-2">
            <!--            {% include "sidebar.html" %}-->
        </div>
        <div class="col-sm-12 col-md-9 col-lg-10 p-2">
            <div id="content" class="border-top border-secondary">
                <div class="content_block">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
</div>
<!-- jQuery JS -->
<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>

<!-- 자바스크립트 블럭 -->
{% block script %}
{% endblock %}

</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/home.html
{% extends 'base.html' %}
<!--static 폴더를 불러옴-->
{% load static %}

{% block extra-style %}
<style type="text/css">
.home-image {
    background-image: url("{% static 'img/img.jpg' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: 55%;
    height: 500px;
    border-top: 10px solid #ccc;
    border-bottom: 10px solid #ccc;
    padding: 10px 0 0 10px;
}
.title {
    color: #c80;
    font-weight: bold;
}
.powered {
    position: relative;
    top: 66%;
    color: #cc0;
    font-style: italic;
    text-align: right;
}

</style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="home-image">
        <h2 class="title">Chang</h2>
        <h2 class="powered"><i class="fas fa-arrow-circle-right"></i>think</h2>
    </div>

    <hr style="margin: 10px 0;">

    <div class="row text-center">
        <div class="col-sm-4">
            <h5>자유게시판</h5>
            <div class="card" style="width: 15rem;display:inline-block;">
                <img class="card-img-top" src="{% static 'img/img_b1.jpg' %}" alt="Card image cap">
                <div class="card-body">
                    <p class="card-title" style="text-align:left;">자유게시판</p>
                    <p class="card-title" style="text-align:left;">청약홈자료</p>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <h5>청약홈자료</h5>
            <div class="card" style="width: 15rem;display:inline-block;">
                <img class="card-img-top" src="{% static 'img/img_b2.jpg' %}" alt="Card image cap">
                <div class="card-body">
                    <p class="card-title" style="text-align:left;">분양권 실거래가</p>
                    <p class="card-title" style="text-align:left;">아파트 실거래가</p>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <h5>부동산관련자료</h5>
            <div class="card" style="width: 15rem;display:inline-block;">
                <img class="card-img-top" src="{% static 'img/img_b3.jpg' %}" alt="Card image cap">
                <div class="card-body">
                    <p class="card-title" style="text-align:left;">입주예정, 미분양</p>
                    <p class="card-title" style="text-align:left;">공사비지수, kb지수 등</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block footer %}
<footer class="fixed-bottom bg-info">
    <div class="text-white font-italic text-right mr-5">changthink</div>
</footer>
{% endblock %}

templates/image_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        body {
            background-image: url('김태리4.jpg');
            background-repeat : no-repeat;
            }

    </style>
</head>
<body>
<!--이미지가운데로-->
<div style="text-align : center;">
    <img   width="300"  height="300 "  src="김태리4.jpg">
</div>
</body>
</html>

templates/navbar.html
<!-- 네비게이션바 -->
<header class="header clearfix">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'home' %}">Home</a>
            <ul class="nav">
                {% if user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'common:logout' %}" class="nav-link">Welcome, {{user.get_username}}(로그아웃)</a></li>
                <li class="nav-item"><a href="{% url 'pybo:index' %}" class="active nav-link ">게시판</a></li>
                <li class="nav-item"><a href="{% url 'ahome:apply_base' %}" class="nav-link">청약홈자료</a></li>
                <li class="nav-item"><a href="{% url 'ahome:ibju_list' %}" class="nav-link">입주예정</a></li>
                <li class="nav-item"><a href="{% url 'ahome:onsale_list' %}" class="nav-link">미분양</a></li>
                <li class="nav-item"><a href="{% url 'ahome:pop_list' %}" class="nav-link">인구세대수</a></li>
                <li class="nav-item"><a href="{% url 'ahome:const_list' %}" class="nav-link">공사비지수</a></li>
                <li class="nav-item"><a href="{% url 'ahome:pjcode_list' %}" class="nav-link">pjcode</a></li>
                <li class="nav-item"><a href="{% url 'ahome:pj_list' %}" class="nav-link">사업관리</a></li>

                {% else %}
                <li class="nav-item"><a href="{% url 'common:login' %}" class="nav-link">로그인</a></li>
                <!--<li class="nav-item"><a href="{% url 'common:signup' %}" class="nav-link">회원가입</a></li>-->
                {% endif %}
            </ul>
        </nav>
    </div>
</header>

templates/navbar2.html
<header class="header clearfix">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'home' %}">Home</a>
            <ul class="nav">
                {% if user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'common:logout' %}" class="nav-link">Welcome,
                    {{user.get_username}}(로그아웃)</a></li>
                <li class="nav-item"><a href="{% url 'pybo:index' %}" class="active nav-link ">게시판</a></li>
                <li class="nav-item"><a href="{% url 'ahome:apply_base' %}" class="nav-link">청약홈자료</a></li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        실거래가자료
                    </a>
                    <ul class="dropdown-menu" style="font-size:14px;">
                        <li><a class="dropdown-item" href="{% url 'rtp:search' %}">분양권실거래가</a></li>

                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'rtp:search_sma' %}">아파트실거래가_수도권</a></li>
                        <li><a class="dropdown-item" href="{% url 'rtp:search_big6' %}">아파트실거래가_지방광역시</a></li>
                        <li><a class="dropdown-item" href="{% url 'rtp:search_dodo' %}">아파트실거래가_팔도</a></li>

                    </ul>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        부동산관련
                    </a>
                    <ul class="dropdown-menu" style="font-size:14px;">
                        <li><a class="dropdown-item" href="{% url 'ahome:ibju_list' %}">입주예정</a></li>
                        <li><a class="dropdown-item" href="{% url 'ahome:onsale_list' %}">미분양</a></li>
                        <li><a class="dropdown-item" href="{% url 'ahome:pop_list' %}">인구세대수</a></li>
                        <li><a class="dropdown-item" href="{% url 'ahome:const_list' %}">공사비지수</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'ahome:rtech_list' %}">부동산테크</a></li>
                        <li><a class="dropdown-item" href="{% url 'ahome:table_list' %}">부동산원 실거래가격지수1</a></li>
                        <li><a class="dropdown-item" href="{% url 'ahome:tbl_kb50' %}">KB선도아파트50지수</a></li>
                        <li><a class="dropdown-item" href="{% url 'ahome:tbl_pir' %}">KB PIR</a></li>
                        <li><a class="dropdown-item" href="{% url 'ahome:tbl_floorarea' %}">용적률</a></li>
                    </ul>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        사업관리
                    </a>
                    <ul class="dropdown-menu" style="font-size:14px;">
                        <li><a class="dropdown-item" href="{% url 'ahome:pjcode_list' %}">사업코드</a></li>
                        <li><a class="dropdown-item" href="{% url 'ahome:tbl_allpj' %}">ALL_PJ</a></li>
                        <li><a class="dropdown-item" href="{% url 'ahome:pj_list' %}">PART_PJ</a></li>
                        <li><a class="dropdown-item" href="{% url 'photo:brand_list' %}">참고_unit</a></li>
                        <li><a class="dropdown-item" href="{% url 'photo:viewimg_list' %}">참고_조감도</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>

                <!--<li class="nav-item dropdown">-->
                    <!--<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"-->
                       <!--aria-expanded="false">-->
                        <!--기타자료-->
                    <!--</a>-->
                    <!--<ul class="dropdown-menu" style="font-size:14px;">-->
                        <!--<li><a class="dropdown-item" href="{% url 'photo:photo_list' %}">평면도</a></li>-->
                        <!--<li><a class="dropdown-item" href="{% url 'photo:photo_upload' %}">평면도업로드</a></li>-->
                        <!--<li><a class="dropdown-item" href="#">기타</a></li>-->
                        <!--<li><a class="dropdown-item" href="#">기타</a></li>-->
                        <!--<li>-->
                            <!--<hr class="dropdown-divider">-->
                        <!--</li>-->
                        <!--<li><a class="dropdown-item" href="#">Something else here</a></li>-->
                    <!--</ul>-->
                <!--</li>-->


                {% else %}
                <li class="nav-item"><a href="{% url 'common:login' %}" class="nav-link">로그인</a></li>
                <!--<li class="nav-item"><a href="{% url 'common:signup' %}" class="nav-link">회원가입</a></li>-->
                {% endif %}
            </ul>
        </nav>
    </div>
</header>

templates/sidebar.html
<nav id="sidebar" class="border-top border-secondary">
    <div class="list-group">
        <a class="rounded-0 list-group-item list-group-item-action list-group-item-light {% if category.name == 'qna'  %}active{% endif %}" href="{% url 'pybo:question_list' %}">질문과답변</a>
        <a class="rounded-0 list-group-item list-group-item-action list-group-item-light {% if category.name == 'free' %}active{% endif %}" href="{% url 'pybo:question_list' %}">자유게시판</a>
        <a class="rounded-0 list-group-item list-group-item-action list-group-item-light {% if category.name == 'tip'  %}active{% endif %}" href="{% url 'pybo:question_list' %}">팁과강좌</a>
        <a class="rounded-0 list-group-item list-group-item-action list-group-item-light {% if category.name == 'quiz' %}active{% endif %}" href="{% url 'pybo:question_list' %}">파이썬퀴즈</a>
        <a class="rounded-0 list-group-item list-group-item-action list-group-item-light {% if category.name == 'bug' %}active{% endif %}" href="{% url 'pybo:question_list' %}">버그및건의</a>
    </div>
</nav>

<ul class="my-3 small" style="padding-left:2em;">
    <li class="my-1"><a href="https://wikidocs.net/book/1" target="_blank">점프 투 파이썬</a></li>
    <li class="my-1"><a href="https://wikidocs.net/book/4223" target="_blank">점프 투 장고</a></li>
    <li class="my-1"><a href="https://wikidocs.net/book/4542" target="_blank">점프 투 플라스크</a></li>
</ul>